### ISSUE TITLE
Urban meeting - list of topics

### ISSUE THREAD

**Issue by korzewski** [atomiklabs/atomiklabs.io#7]
Let's fill up this document https://blockyblokes.atlassian.net/wiki/spaces/MAIN/pages/40501249/Urban+meeting+-+list+of+topics

**Comment by tk-o** [comment]
We learnt that:
- to receive an Open Grant, we need to have a legal entity;
  - Ubran mentioned that he would introduce us to David who is managing the grants in W3F;
- to be accepted into the Substrate Builders Program, we need to have a track record (for example, a successfully completed grant) and a business model (we need to know how to commercialize our efforts);
- we mentioned an idea of the Substrate-in-a-box — Urban seemed to like this one, as it supports the ecosystem to focus on building their domain logic, and not focus to much on the configuration;
- we also mentioned our plan for _Node.js extensions for off-chain worker_, but it didn't seem to make sense to Urban (commercially).
